version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: pds_kafka
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092, CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  show-catalog-postgres:
    image: postgres
    container_name: pds_postgres
    platform: linux/amd64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pds
      POSTGRES_PASSWORD: pds
      POSTGRES_DB: pds

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080

  showcatalog:
    image: pdsgrupo2/show-catalog-service:latest
    #image: show-catalog-service
    container_name: showcatalog
    depends_on:
      - pds_postgres
      - kafka
    ports:
      - 18081:18081

  notification:
    image: pdsgrupo2/notification-service:latest
    #image: notification-service
    container_name: notification
    ports:
      - 18082:18082

  apigateway:
    image: pdsgrupo2/api-gateway:latest
    container_name: apigateway
    ports:
      - 8081:8081

networks:
  default:
    external:
      name: pdsnet
